<?php

class BitrixEcommerce extends CBitrixComponent
{
    public function onPrepareComponentParams($arParams)
    {
        return parent::onPrepareComponentParams($arParams); // TODO: Change the autogenerated stub
    }

    public function executeComponent()
    {
        $this->includeComponentTemplate();
    }
}